sudo: required
dist: xenial
language: generic
services:
  - docker
install:
  - docker pull aergus/latex
script:
  - docker run --rm -it -v$(pwd):/fisica-tecnica-cheatsheet -w /fisica-tecnica-cheatsheet aergus/latex bash -c 'latexmk -pdf -f fisica-tecnica.tex || true'
branches:
  except:
    - /^travis-.*/

before_deploy:
  - git config --local user.name "Travis Builder"
  - git config --local user.email "travis@travis.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-travis-$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "EwlC8XRQjJNApgyqRV5yyijv87Mf7xAe34X+1qulm5li4jOg/hGQFNtZiDjOfOQNrzeYecsuG2dN5KAl+svWPLYhvfRKhoy2AOt2k3GC9C+TEiP0TYisJ9hFntJAnmUREpDl+LiqEkeUNPcq3AMYZIhHWaZLa6+EeIJ9912XIkO/52IvVA1VyouVUeV0BTbBcsgDW/3QNscn3tVuF1HWNq8mEWBvC46Sfz+q4UIdXxuU1F/WAzSyygo82JCk2u6CWo3NFOOCsCLUXVrWVb4FG/CAW7NWmzBNCTNliB814f+2snq7MJeDkaiXcy5aQ/R4aY3VmX+OX/dmpoJelJ1sdMsAF/qyPdXLu7R64HeIXRWvXx5ZWPvkfZ/h+ChzBR4VXImF4C+0BxM0KnsS2iNAN/Ih1mJe0gOaMtOyCTxU1XPfLJXHd/0S6Wn0kEWnTZZb1fmtepQ71EAP0Xl4vtR3bf1JemreeFdmvh+zJUrKwM/Y7V6Sq86uMdCRR36UYmnbvrk7Ktrjzv6n1l9MyNiyDWAJ3D3lNzkWBN8+odYy5R5mtEWJoWPB9xs6R7BWPelwjofcV2m7cSoTBt/97eW3NPeWKjauMRhWEVi2Y1kT874QWUtaAvSmedGzCNcWC9fEpBll1YmzRKuIdx3b9Nv9J4kmVvLPsuz0bPr4JK9QNNs="
  file: fisica-tecnica.pdf
  skip_cleanup: true
