sudo: required
dist: xenial
language: generic
services:
  - docker
install:
  - docker pull aergus/latex
script:
  - docker run --rm -it -v$(pwd):/fisica-tecnica-cheatsheet -w /fisica-tecnica-cheatsheet aergus/latex bash -c 'latexmk -pdf -f fisica-tecnica.tex || true'
branches:
  except:
    - /^travis-.*/

before_deploy:
  - git config --local user.name "Travis Builder"
  - git config --local user.email "travis@travis.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-travis-$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "Nl7BtAMIrEdEfmszdnCy0pBWyfRy3pqI8jBAsMhhNX9L7HymE+ejCJmy3AghUnogL1htd3D7KtqZAwffnKQCAShbs2Q5meqBipM78KMXql/2XSat8qGd0XAJBbjiQq5VL3D8s0RrBOrBl/t/6gXKgNBmiZH9zp+7J44rNSVc5bSHrMUxHa+6+aJ7P367hqAs1TSWpsyAZPck/GqNcioWSWvQ77vNyLLsYcYOqAqVA2vORist4m135zi4kKVxCxiE3Uh3QtkMBBA//Ez0pWdb9eWWHTnubQ+wuQcgXeZR8PU9rSgBP5+99HK3GLgKEu/lhZAsnMDjcJf0uXncCc8Edq+a/AOR0UhR8rqPTHRsOVY5mBNp7WHvNJuMizuUuRoLtvYx8i6cqBV8aZMWIb0yxMNY+tWRYzJRtavf4I8xMAqTMqyh9e7afJ5ZvzJgDFpCr/NH0FsJShPmU+6soDasUDn7lUr2fzlaP0Aoki2F4HLbFkLyhYI2YyRKJg9iq9fSyR/kuBbuAHKwuJElV9eKoX6VlmwyJ0VUCltZnSUyKGcloLC7HoVtLvMXFPsLp+ypu9R8y9zZ6t2yQ4UUga5An0y9do52rmh/cW3JMQzdNMqnI0EKj3k1oVutGclYCiNIUmWQqkzrs7ehfBoB/iCbVBbgzlIQefS43TQrYyEFgts="
  file: fisica-tecnica.pdf
  skip_cleanup: true
